### ISSUE TITLE
Please give example of appsettings.json

### ISSUE THREAD

**Issue by michaelkruglos** [MindscapeHQ/serilog-sinks-raygun#18]
Serilog can be configured using appsettings.json.
Please provide an example of appsettings.json with configuration for Raygun sink.

**Comment by nblumhardt** [comment]
Hi! Not sure if it helps, but SerilogAnalyzer can generate JSON configuration for you automatically; see: https://github.com/Suchiman/SerilogAnalyzer.

**Comment by grugcrood82** [comment]
"Serilog": {
        "Using":  ["Serilog.Sinks.Raygun"],
        "MinimumLevel": "Information",
        "WriteTo": [ {
            "Name": "Raygun",
            "Args": {
                "applicationKey": "abc"
            }
        }]
    }

**Comment by j5alive** [comment]
I have an update to the project [readme.md](https://github.com/serilog/serilog-sinks-raygun/pull/42/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R28) file coming with PR #42 that gives an example on how to do this.

This issue can be closed.
