### ISSUE TITLE
New organization required for this repository

### ISSUE THREAD

**Issue by nblumhardt** [MindscapeHQ/serilog-sinks-raygun#46]
Hi @serilog/reviewers-raygun 👋 

Via https://github.com/serilog/serilog/issues/1627 - we're unbundling the `serilog` organization to help distribute the effort involved in managing the various Serilog sub-projects. The `serilog` organization will now only manage the fundamental sinks and other packages that the rest of the ecosystem builds upon.

If this package is actively maintained, it can be moved to a new organization managed by the maintainers (ideally @MindscapeHQ). Otherwise, it can move to the `serilog-archive` parking lot, from where we hope a new community-run fork might spring from in the future 🌷 .

Let me know if you're a maintainer and keen to continue this project under a new org; otherwise, I'll shuffle things around and move this one to the archive.

Thanks!

**Comment by QuantumNightmare** [comment]
Hey @nblumhardt

Thanks for reaching out. Raygun is able to take ownership of this Serilog sink. The GitHub repo can be managed under @MindscapeHQ, and the NuGet package listed [here](https://www.nuget.org/profiles/mindscapehq).

**Comment by nblumhardt** [comment]
Thanks for the reply, @QuantumNightmare! It looks like someone from @MindscapeHQ will need to perform the repository transfer - are you right person for that?

NuGet package is transferred 👍

**Comment by QuantumNightmare** [comment]
Interesting, I thought you'd just need to transfer ownership of this repository to the @MindscapeHQ org without needing to specify an individual. I don't have admin privileges in @MindscapeHQ for anything that needs to be actioned on that side, so try either @cmdrKeen or @turtlespin (they are both aware of this move). Nor do I have access to the Transfer Ownership controls of this repository as far as I can tell.

**Comment by nblumhardt** [comment]
Thanks @QuantumNightmare! I've invited @CmdrKeen to become an admin of this repo and perform the transfer (👋), and also invited the `mindscapehq` NuGet organization to become an owner of the package.

Because of "blue tick" requirements it'll take a little longer to remove the `serilog` org as a package owner; working with the NuGet team to do that in: https://github.com/NuGet/NuGetGallery/issues/8844.

**Comment by QuantumNightmare** [comment]
Will likely continue this next week

**Comment by QuantumNightmare** [comment]
We have transferred this repository to the MindscapeHQ org.

@nblumhardt Is there anything else that's required to be transferred, e.g. AppVeyor or automated deployment to NuGet? I remember in the past there have been times when you'd needed to update NuGet authentication keys. Could you please point us towards how this is done if necessary.

**Comment by nblumhardt** [comment]
🎉 that's great, thanks for the update.

RE AppVeyor, you'll need to create a new project pointing to this repo - should be a very quick change, as all of the configuration is in _appveyor.yml_.

Following that, using your NuGet organization, create a new API key. Then in AppVeyor, go to Account > Encrypt YAML, encrypt the key, and copy the result into _appveyor.yml_.

Also good to remember to update the build badge in the README to point to the new CI project.

HTH, give me a yell if you get stuck on anything.

I'll follow up with the NuGet folks shortly about removing `serilog` as a package owner.

**Comment by nblumhardt** [comment]
Hi @QuantumNightmare - I've just realised that the NuGet.org transfer hasn't been accepted yet. Whoever manages the `mindscapehq` account on NuGet should have an email invitation to accept ownership - would it be possible to check in on this?

I'm coordinating with the NuGet team to get the `serilog` owner removed (bug around changing ownership of "blue tick" packages), so to avoid double-handling for them, I've temporarily added my own account `nblumhardt` as a co-owner, which one of us can remove once `mindscapehq` has accepted.

Thanks! :-)

**Comment by QuantumNightmare** [comment]
Hey @nblumhardt, thanks for pointing this out, we'd missed that email. We have now accepted the invitation to become an owner of the NuGet package. As a note, we are yet to set up AppVeyor.

**Comment by nblumhardt** [comment]
Thanks @QuantumNightmare! I've removed myself as an owner now. As far as I can tell this ticket is now complete.

Good luck with it, and let me know if there's ever anything I can help with.

**Comment by QuantumNightmare** [comment]
No worries and thanks to you too. Will get in touch if something comes up.
